# Generated by Django 4.1.3 on 2022-11-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_produto_slug_alter_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='tipo',
            field=models.CharField(default='indefinido', max_length=50, verbose_name='Tipo'),
        ),
    ]
